### PR TITLE
Additional MDM control and specific additions to support Intune for 3.0 codebase

### PR DESCRIPTION
**Pull request by gilburns**
- Added logic to read most settings from MDM configuration instead of using embedded script variables. (This is usable with any MDM solution.) This required a bit of re-arranging the login in **get_preferences** function. (Required moving the writing of the app labels to the plist at the end of the function. That way MDM passed labels could be read in first.)
- Added icon support for Intune overlay.
- Added logic for webhook messages to support Intune as an alternate MDM provider.
- Standardized some of the options variables used to match naming like the others.
- Fixed some of the formatting. There are sections that use 4 spaces and others that use tabs. In functions that I edited I used the 4 space option, as most of the script uses that standard. (Might be good to add an **.editorconfig** file to the project?)
- Added an Intune configuration file example

### CODE REVIEW

**Comment by gilburns** [comment]
Let me know if there's any questions. Thanks!

**Comment by TechTrekkie** [comment]
> Let me know if there's any questions. Thanks!

Sounds good! Thanks for the PR! I'll be posting beta 2 today with some additional features and will look at including this PR with that update.

**Comment by gilburns** [comment]
Some of my reasoning behind the changes submitted:

Part of my goal with this PR, and I feel like it should already be the projects goal as well, is to support as much config as possible via MDM. That way when the next update to 3.x comes out, I don't even have to remember to update the embedded script variables. I can simply replace the existing script with the newer version without having to stop and edit variables first. (This will be helpful for the Jamf admins as well)

Secondly, many other Mac management solutions, Intune included, cannot pass arguments to the script at runtime. So to more broadly enable other management solutions, adding the MDM config is required instead of only supporting script arguments.

**Comment by gilburns** [comment]
Thinking it might be a lot for one PR. Would you prefer I split it up into multiple smaller PRs for the changes?

**Comment by TechTrekkie** [comment]
No that’s ok, it seems pretty straightforward. Thank you though On Nov 10, 2024, at 1:13 PM, Gil Burns ***@***.***> wrote:﻿
Thinking it might be a lot for one PR. Would you prefer I split it up into multiple smaller PRs for the changes?

**Comment by TechTrekkie** [comment]
What's crazy is that I could have sworn we had the label variables as managed MDM options, but maybe that was another test version from earlier that we forgot to merge. 
But that was definitely our goal as well to have everything available as MDM options.

**Review by TechTrekkie — APPROVED** [review]

**Pull request merged**
